### ISSUE TITLE
uBo lite detected on megaup.net

### ISSUE THREAD

**Issue by 424344** [uBlockOrigin/uBOL-issues#15]
### Prerequisites

- [X] This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of uBlock Origin

### I tried to reproduce the issue when...

- [X] uBO is the only extension
- [X] uBO with default lists/settings
- [X] using a new, unmodified browser profile

### URL(s) where the issue occurs

`https://megaup.net/1aknk/sc23898-TSOMISE.rar`

### Describe the issue

uBlock is detected when loading megaup.net pages with optimal or complete settings.
when using basic setting uBlock is not detected and some ads are blocked, but I still see many ads that are not blocked.

### Screenshot(s)

basic is not detected but many ads are not blocked
![image](https://user-images.githubusercontent.com/26486758/204540044-231c9c58-8b46-49d9-b8f6-6c40b1303ed7.png)

optimal and complete is detected:
![image](https://user-images.githubusercontent.com/26486758/204540123-90429056-8a58-44bf-8fd1-6b16934e3a73.png)

### uBlock Origin version

uBlock Origin Lite 0.1.22.11165

### Browser name and version

Edge Version 107.0.1418.62 (Official build) (64-bit)

### Settings

![image](https://user-images.githubusercontent.com/26486758/204540365-40a0fa7f-b3a4-41e4-a97e-7812301b4090.png)

**Comment by mapx-** [comment]
use the normal uBO in firefox for example, the redirect filters don't work in mv3 (uBOL)

**Comment by gorhill** [comment]
I see two filters enforced in uBO's logger for that site which can't be directly converted to MV3:

- `*$frame,redirect-rule=noopframe,domain=megaup.net`
- `/^https?:\/\/(?:[a-z]{2}\.)?[0-9a-z]{7,16}\.com\/[a-z](?=[a-z]{0,25}[0-9A-Z])[0-9a-zA-Z]{3,26}\/(?:[1-5]\d{4}|[3-9]\d{3})\??(?:_=\d+|v=\d)?$/$script,redirect-rule=noop.js`

First one might be converted to a `redirect` rule, but second one is not convertible because the regex is not supported in MV3.

Solution is to use uBO, I can't make the regex work in uBOL, it's an MV3 API limitation.

**Comment by dotproto** [comment]
Thanks for creating the [mv3 hardship](https://github.com/uBlockOrigin/uBOL-issues/labels/mv3%20hardship) label, @gorhill. I'm hoping this label will help inform discussions at the WECG and in Chrome.

AFAIK the regular expression doesn't work in MV3 because Chrome uses RE2 for dNR regular expression matching and RE2 doesn't support lookarounds. I think that if `(?=[a-z]{0,25}[0-9A-Z])` were dropped from the rule it could be used in uBOL. Unfortunately, in my testing I didn't see any requests that matched the original RegExp, so I'm not confident that removing the lookahead won't have unintended side effects.

**Comment by gorhill** [comment]
> I think that if `(?=[a-z]{0,25}[0-9A-Z])` were dropped from the rule it could be used in uBOL.

That part is important as it prevent false positives, and also it's not so sure it would still work in uBOL, consider these regexes which are currently rejected by DNR:

- `/(https?:\/\/)104\\.154\..{100,}/`
- `/\/[0-9a-z]{8,10}\?shu=[0-9a-z]{150,}/`

It's just a sample, I currently see 39 regexes with no lookaround part in default filterset which are refused by the DNR API because of `memoryLimitExceeded` reason.

**Comment by dotproto** [comment]
Thanks for the clarification. The memory limit for compiled RE2 expressions slipped my mind. I feel like it should be possible to rewrite that expression to avoid lookarounds (and am trying hard not nerdsnipe myself with this), the compiled expression may be too large for dNR's current limits.

@gorhill, if it's not too much trouble, would it be possible to get a gist/paste/whatever with those 39 rules? I think dNR rules would be best, but even just the list of RegExps would be quite helpful.

**Comment by mapx-** [comment]
@dotproto you can take a look here:

https://github.com/gorhill/uBlock/blob/master/dist/mv3/log.txt

searching for `RE2-compatible`

**Comment by gorhill** [comment]
The rejected regexes are reported ar the dev tools console of uBO Lite when installing or reloading the extension. I am not at the desktop computer now.

**Comment by Yuki2718** [comment]
> The rejected regexes are reported at the dev tools console of [uBO Lite](https://chrome.google.com/webstore/detail/ublock-origin-lite/ddkjiahejlhfcafbddmgiahcphecmpfh) when installing or reloading the extension.

Sorry, how can I see this? I don't see anything on Console of background or dashbord when I refresh the page or disable-enable uBOL.

**Comment by gorhill** [comment]
You need to install uBOL as a local package. Download from [releases](https://github.com/uBlockOrigin/uBOL-home/releases). For chromium, unzip then load with "Unload unpacked". For Firefox go to `about:debugging#/runtime/this-firefox`, then "Load As Temporary Add-on..."
