### ISSUE TITLE
Permissions acting weird

### ISSUE THREAD

**Issue by atifhussain18** [uBlockOrigin/uBOL-issues#22]
I've set uBOL on basic mode. So there are no permissions granted to the extension.
But on clicking the extension the extension supposedly received "access to the site". 

This is how uBOL looks like when the extension icon isn't clicked.
![image](https://user-images.githubusercontent.com/47064709/209534477-1ae271ee-2393-416b-9e08-c1db61195be6.png)

This is what it looks like after i click on the extension icon or open the extensions overflow menu in chrome without granting any additional permission
![image](https://user-images.githubusercontent.com/47064709/209534463-b55e7ddc-fb61-4ede-b27c-5a4636e401ca.png)

**Comment by gorhill** [comment]
Remove the _All sites_ permission from the extension details:

![Screenshot from 2022-12-26 09-19-17](https://user-images.githubusercontent.com/585534/209558086-cc14fcb5-cdd2-4407-8213-06b02930e73c.png)

Whenever you explicitly grant permissions on all sites by selecting _Optimal_ or _Complete_ mode, going back to _Basic_ won't revoke the broad permissions, you have to remove them manually. The reason why broad permissions are not revoked once granted is because you could have specific websites which are set to work in _Optimal_ or _Complete_ mode, and these would stop working as expected if broad permissions were revoked.

**Comment by gorhill** [comment]
Disregard part of my answer above, I should have checked first, but I looked through the code and I do actually call `browser.permissions.remove({ origins: [ '<all_urls>' ] })` when selecting _Basic_ mode, and this works fine on my side, there is no more broad permissions after selecting _Basic_. Are you sure uBOL was effectively in _Basic_ mode when you checked the permissions? Please provide screenshot of settings page in uBOL.

**Comment by gorhill** [comment]
Ok I look more carefully into what you are reporting. I think it's just Chromium user interface not reporting accurately, since what it reports in that little popup panel does not match what it reports in the extensions _Details_, i.e. _"This extension has no additional site access"_ beside _"Block content on any page"_.

**Comment by atifhussain18** [comment]
> Ok I look more carefully into what you are reporting -- I deleted my previous misguided answers. I think it's just Chromium user interface not reporting accurately, since what it reports in that little popup panel does not match what it reports in the extensions _Details_, i.e. _"This extension has no additional site access"_ beside _"Block content on any page"_.

Also I noticed this issue gets resolved if we open the same website in a new tab. The extension again shows "wants access to site" until you click on it again. Maybe it's somehow related to the chrome setting for extensions to give access to site data "when you click on extension". 
![image](https://user-images.githubusercontent.com/47064709/209613949-c4ecbb16-0f0f-4acc-86da-ae100a8103ee.png)

**Comment by gorhill** [comment]
Closing as _external_, it seems Chromium is improperly reporting the current state of permissions.
