### ISSUE TITLE
sb.scorecardresearch.com not being blocked in uBlock Origin Lite

### ISSUE THREAD

**Issue by hj-collab** [uBlockOrigin/uBOL-issues#23]
### Prerequisites

- [X] This is not a support issue or a question. For support, questions, or help, visit [/r/uBlockOrigin](https://www.reddit.com/r/uBlockOrigin/).
- [X] I performed a [cursory search of the issue tracker](https://github.com/uBlockOrigin/uAssets/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I am running the latest version of uBlock Origin (uBO).

### I tried to reproduce the issue when...

- [X] uBO is the only extension.
- [X] uBO uses default lists and settings.
- [X] using a new, unmodified browser profile.

### Description

sb.scorecardresearch.com is being blocked in uBlock Origin but not in the lite version.

### URL(s) where the issue occurs.

`https://sb.scorecardresearch.com/`

### uBO version

Latest

### Browser name and version

Chromium Edge

### Settings

None.

**Comment by gorhill** [comment]
Can you be more specific? Are you talking about [strict-blocking](https://github.com/gorhill/uBlock/wiki/Strict-blocking)?

**Comment by mapx-** [comment]
What page were you visiting when you realized that `scorecardresearch` is not blocked?

**Comment by gorhill** [comment]
You need to tell us what to do in details for us to reproduce on our side.

**Comment by krystian3w** [comment]
On my side request/resources are blocked (homepage lost 1-st party CSS&images, can't by loaded e.g. as 3-rd party iframe, someone should checking pop-ups and popunders).

To enable these strict blocking **fallback**:

> ### The site `sb.scorecardresearch.com` is blocked
> This site has been blocked by an extension <br><br>
> 
> Try disabling extensions.
> 
> ERR_BLOCKED_BY_CLIENT


I think needed change something in converter for HOSTS and EL syntax:

```adb
0.0.0.0 fo1.bar7.com
||foo.bar7.com^
```

I assume that it is not yet safe to convert "this" (e.g. no possible simple implement pause instead disable all filtering):

```json
 {
    "_comment": "this can be invalid demo DNR rule (handwritten)"
    "action": {
      "type": "block"
    },
    "condition": {
      "requestDomains": [
        "scorecardresearch.com"
       ]
    }
   "resourceTypes": [
        "main_frame"
   ]
 }
```

I have not determined whether it is possible to overwrite it with some detailed message of the reason for the blockade, but in AdGuard MV3 a little works `click2load.html` (so don't corectly removed incompatible scriptlets, because injected code don't have visible text and working "button" also no support frames redirecting) - url has changed.
